name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Добавляем явное указание на необходимые секреты
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SERVER_HOST }}
          if_key_exists: replace
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh $SSH_USER@$SERVER_HOST << 'ENDSSH'
            cd /root/media-video-maker
            git pull origin main
            docker-compose down
            docker-compose build
            docker-compose up -d
          ENDSSH